% Auto generated function to compile/launch Vivado Simulator simulator
% 
% Generated by MATLAB 24.1 and HDL Coder 24.1

function launch_quantumComputer_twoQubit_fixpt_cosim
[s,r] = system('vivado -mode batch -source C:\Doc\github\Quantum\Code\matlab\two_qubit_system\codegen\quantumComputer_twoQubit\cosim\launch_quantumComputer_twoQubit_fixpt_cosim.tcl','-echo');
if s
   error('Failed to create Vivado HDL design DLL using script C:\Doc\github\Quantum\Code\matlab\two_qubit_system\codegen\quantumComputer_twoQubit\cosim\launch_quantumComputer_twoQubit_fixpt_cosim.tcl.');
end


