% Function localRecompile_quantumComputer_twoQubit_wrapper_fixpt_cosim recreates a MEX-function quantumComputer_twoQubit_wrapper_fixpt_cosim_mex from MATLAB function quantumComputer_twoQubit_wrapper_fixpt_cosim
% Generated by MATLAB 24.1 and HDL Coder 24.1
function localRecompile_quantumComputer_twoQubit_wrapper_fixpt_cosim

load('C:\Doc\github\Quantum\Code\matlab\two_qubit_system\codegen\quantumComputer_twoQubit\cosim\localCodegenArgs_quantumComputer_twoQubit_wrapper_fixpt_cosim');

fxptPath = 'C:\Doc\github\Quantum\Code\matlab\two_qubit_system\codegen\quantumComputer_twoQubit\fixpt';
addpath(fxptPath);
cleanupObj = onCleanup(@() rmpath(fxptPath));
codegen -args exInputs -o 'C:\Doc\github\Quantum\Code\matlab\two_qubit_system\codegen\quantumComputer_twoQubit\cosim\quantumComputer_twoQubit_wrapper_fixpt_cosim_mex' quantumComputer_twoQubit_wrapper_fixpt_cosim;

