% Auto generated function to execute the generated cosimulation test bench
% 
% Generated by MATLAB 24.1 and HDL Coder 24.1

function run_quantumComputer_twoQubit_fixpt_cosim

% Launch HDL simulator
disp('### Launching Vivado Simulator for cosimulation ');
launch_quantumComputer_twoQubit_fixpt_cosim;

% Clear persistent variables before simulation
l_clearPersistentVariable;

% Clear persistent variables after simulation
onCleanupObj = onCleanup(@() l_clearPersistentVariable);

% Add current working directory to search path
savedPathVar = addpath(pwd);
restorePathObj = onCleanup(@() path(savedPathVar));

% Run generated test bench
disp('### Simulating generated test bench ');
% Exercise the compiled version of quantumComputer_twoQubit_wrapper_fixpt_cosim in the generated test bench.
% To debug the test bench with the original function "quantumComputer_twoQubit_wrapper_fixpt_cosim",
% replace the next line with "quantumComputer_twoQubit_tb_cosim"
coder.runTest('localRunTest_quantumComputer_twoQubit_fixpt','quantumComputer_twoQubit_wrapper_fixpt_cosim');
% To recompile MATLAB function "quantumComputer_twoQubit_wrapper_fixpt_cosim",
% run the re-compilation function "localRecompile_quantumComputer_twoQubit_wrapper_fixpt_cosim".
disp('### Finished Simulation');

end

function l_clearPersistentVariable
% Clear reference DUT function
clear quantumComputer_twoQubit_fixpt;

% Clear cosimulation System object wrapper function
clear quantumComputer_twoQubit_fixpt_sysobj_cosim;

% Clear cosimulation function
clear quantumComputer_twoQubit_fixpt_cosim;

% Clear generated MEX function
clear quantumComputer_twoQubit_wrapper_fixpt_cosim_mex

end

