%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [computerState,probFinal,probQubit0,probQubit1] = quantumComputer_twoQubit_wrapper_fixpt(opName_0,theta_0,phi_0,lambda_0,opName_1,theta_1,phi_1,lambda_1,initState_0,initState_1)
    fm = get_fimath();
    opName_0_in = opName_0;
    theta_0_in = theta_0;
    phi_0_in = phi_0;
    lambda_0_in = lambda_0;
    opName_1_in = opName_1;
    theta_1_in = theta_1;
    phi_1_in = phi_1;
    lambda_1_in = lambda_1;
    initState_0_in = initState_0;
    initState_1_in = initState_1;
    [computerState_out,probFinal_out,probQubit0_out,probQubit1_out] = quantumComputer_twoQubit_fixpt( opName_0_in, theta_0_in, phi_0_in, lambda_0_in, opName_1_in, theta_1_in, phi_1_in, lambda_1_in, initState_0_in, initState_1_in );
    computerState = computerState_out;
    probFinal = probFinal_out;
    probQubit0 = probQubit0_out;
    probQubit1 = probQubit1_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
