%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%          Generated by MATLAB 24.1 and Fixed-Point Designer 24.1          %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [computerState,probFinal] = quantumComputer_oneQubit_wrapper_fixpt(opName,theta,phi,lambda,initState)
    fm = get_fimath();
    opName_in = opName;
    theta_in = theta;
    phi_in = phi;
    lambda_in = lambda;
    initState_in = initState;
    [computerState_out,probFinal_out] = quantumComputer_oneQubit_fixpt( opName_in, theta_in, phi_in, lambda_in, initState_in );
    computerState = computerState_out;
    probFinal = probFinal_out;
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
