function probFinal = probFinal_oneQubit(a)
    fm = fimath('RoundingMethod','Nearest',...
            'OverflowAction','Saturate', ...
            'ProductMode','SpecifyPrecision', ...
            'ProductWordLength', 16, ...
            'ProductFractionLengthg', 15, ...
            'SumMode', 'SpecifyPrecision', ...
            'SumWordLength', 16, ...
            'SumFractionLengthg', 15, ...
            'CastBeforeSum', true);
    nt = numerictype(0,16,16);
    probFinal = fi([0;0],nt,fm);
    abs_value = cordicabs(a,15);
    probFinal(:) = abs_value.*abs_value;
end